const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');const env={window:{}};env.window=env;vm.createContext(env);vm.runInContext(fs.readFileSync(__dirname+'/../js/physics.js','utf8'),env);const {Car}=env.CD;const settings={response:6,returnRate:4};let count=0;function test(name,fn){fn();console.log('PASS',name);count++;}function drive(p,input,n=120){for(let i=0;i<n;i++)p.update(1/120,input,settings,[]);}
test('Forward acceleration and responsive brakes',()=>{const p=new Car();drive(p,{gas:true,steer:0});assert(p.z<20&&p.speed>2);drive(p,{brake:true,steer:0});assert.equal(p.speed,0);});
test('Right steering turns right; reverse turns opposite',()=>{const p=new Car();drive(p,{gas:true,steer:1});assert(p.yaw>0&&p.x>0);const q=new Car();q.gear=-1;drive(q,{gas:true,steer:1});assert(q.yaw<0&&q.z>20);});
test('Gear change locked in motion, allowed stopped',()=>{const p=new Car();drive(p,{gas:true,steer:0});assert(!p.changeGear(-1));drive(p,{brake:true,steer:0});assert(p.changeGear(-1));});
test('Smooth steering and return to centre',()=>{const p=new Car();p.update(1/120,{steer:1},settings,[]);assert(p.steer>0&&p.steer<.61);drive(p,{steer:0},240);assert(Math.abs(p.steer)<.001);});
test('High speed reduces steering lock',()=>{const p=new Car(),q=new Car();q.speed=12;p.update(.1,{steer:1},settings,[]);q.update(.1,{steer:1},settings,[]);assert(p.steer>q.steer);});
test('Rotated car collision uses full footprint',()=>{const p=new Car();p.yaw=Math.PI/4;assert(p.overlaps({x:1,z:19,w:.5,d:.5}));assert(!p.overlaps({x:8,z:8,w:1,d:1}));});
test('Obstacle collision stops car and counts once',()=>{const p=new Car();const b={x:0,z:15,w:5,d:1};for(let i=0;i<360;i++)p.update(1/120,{gas:true,steer:0},settings,[b]);assert(p.z>17);assert.equal(p.contacts,1);assert.equal(p.speed,0);});
test('Parking requires full containment, alignment and low speed',()=>{const p=new Car();const bay={x:11,z:-20,w:3.6,d:6.4,yaw:0};p.x=11;p.z=-20;assert(p.parked(bay));p.speed=1;assert(!p.parked(bay));p.speed=0;p.yaw=.4;assert(!p.parked(bay));p.yaw=0;p.x=13;assert(!p.parked(bay));});
test('Fixed timesteps yield stable one-second acceleration',()=>{const p=new Car(),q=new Car();for(let i=0;i<120;i++)p.update(1/120,{gas:true,steer:.5},settings,[]);for(let i=0;i<60;i++)q.update(1/60,{gas:true,steer:.5},settings,[]);assert(Math.abs(p.speed-q.speed)<.03);assert(Math.abs(p.x-q.x)<.05);});
console.log(count+' physics checks passed');
